### ISSUE TITLE
Error building due to toggleKey and reloadKey problems

### ISSUE THREAD

**Issue by son-dh** [Akintos/DiscoTranslator#2]
The IDE stopped building at these 2 lines in DiscoTranslatorPlugin.cs:

```
            toggleKey = Config.Bind("Hotkeys", "Toggle interface", new KeyboardShortcut(KeyCode.T, KeyCode.LeftAlt));
            reloadKey = Config.Bind("Hotkeys", "Reload translation", new KeyboardShortcut(KeyCode.R, KeyCode.LeftAlt))
```

> Severity: Error
> Code: CS1061	
> 'ConfigFile' does not contain a definition for 'Bind' and no accessible extension method 'Bind' accepting a first argument of type 'ConfigFile' could be found (are you missing a using directive or an assembly reference?)

All dependencies have been included in the lib folder as instructed, so I'm not sure what am I missing

**Comment by Akintos** [comment]
Maybe you used older version of BepInEx?
You should use BepInEx version over 5.0.

**Comment by Akintos** [comment]
[DiscoTranslator.zip](https://github.com/Akintos/DiscoTranslator/files/4000648/DiscoTranslator.zip)
Use this compiled binary.

**Comment by son-dh** [comment]
I'm using BepInEx 5.0.0.116. BepInEx can see the pluging using your compiled binary, however nothing shows up when I hit Shift + T (to be sure I also tried Ctrl + T or Alt + T). 

This is the excerpt of the log file from BepInEx

```
[Info   :   BepInEx] Loading [Disco Translator 0.1.0.0]
[Error  : Unity Log] MissingMethodException: BepInEx.Configuration.ConfigEntry`1<!!0> BepInEx.Configuration.ConfigFile.Bind<!0>(string,string,!!0,BepInEx.Configuration.ConfigDescription)
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
Sunshine.JsonUtil:ReadFromFile(String, String)
SettingsHolder:RefreshSettingsFromDisk()
SettingsHolder:Get()
SettingsPersister:BoolOrDefault(SETTINGS_CATEGORY, String, Boolean, Boolean)
SettingsPersister:GetBoolOrDefault(SETTINGS_CATEGORY, String, Boolean)
Log:InitDictionary()
Log:.cctor()
GogGalaxyManager:Awake()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DiscoTranslator.DiscoTranslatorPlugin.LoadTranslation () (at <e5a396ca9b7b4ba187869e78e5e1a322>:0)
DiscoTranslator.DiscoTranslatorPlugin.Awake () (at <e5a396ca9b7b4ba187869e78e5e1a322>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
Sunshine.JsonUtil:ReadFromFile(String, String)
SettingsHolder:RefreshSettingsFromDisk()
SettingsHolder:Get()
SettingsPersister:BoolOrDefault(SETTINGS_CATEGORY, String, Boolean, Boolean)
SettingsPersister:GetBoolOrDefault(SETTINGS_CATEGORY, String, Boolean)
Log:InitDictionary()
Log:.cctor()
GogGalaxyManager:Awake()
```

**Comment by Akintos** [comment]
That is strange, latest BepInEx has ConfigFile.Bind() method. I double checked it.
```C#
public ConfigEntry<T> Bind<T>(string section, string key, T defaultValue, string description)
	=> Bind(new ConfigDefinition(section, key), defaultValue, new ConfigDescription(description));
```
https://github.com/BepInEx/BepInEx/blob/master/BepInEx/Configuration/ConfigFile.cs#L312

Can you please check again if you are using latest version of BepInEx?

**Comment by son-dh** [comment]
Woo thanks, it works with the latest BepInEx indeed. Now that 300MB json file is intimidating!
