### ISSUE TITLE
GUI is empty after Hardcore Mode update

### ISSUE THREAD

**Issue by xyrilyn** [Akintos/DiscoTranslator#3]
I was able to access the GUI, load translations, etc before the update, but after the latest (Hardcore Mode) update, the GUI is empty now.

I have tried reinstalling BepInEx + DiscoTranslator to no effect.

**Comment by Akintos** [comment]
I can't tell why it is not working, but rebuilding the plugin with updated game dll files worked.

Please download latest release again.
